### PR TITLE
fix: remove deduplicate fragments (fix #90)

### LINKED ISSUE #90: Handle duplicate fragments
I have a query that uses a fragment directly, and another fragment that uses the same fragment in a nested manner:

```graphql
query getViewerCommunities($id: ID!) {
  user(id: $id) {
    ...userInfo
    communities {
      participants {
        ...communityParticipantInfo
      }
    }
  }
}
${userInfoFragment}
${communityParticipantInfoFragment}
```

With a `communityParticipantInfo` fragment that looks like this:

```graphql
fragment communityParticipantInfo on CommunityParticipant {
  idm
  user {
    ...userInfo
  }
}
${userInfoFragment}
```

As you can see, the `userInfoFragment` is repeated twice. Using `graphql-tag` at runtime correctly deduplicates that fragment and everything works perfectly.

Unfortunately, `graphql.macro` does not deduplicate the fragment and my server thusly throws an error saying "Duplicate fragment" and rejects the query entirely.

### PR DESCRIPTION
**Pull request by FezVrasta**
With this PR, we deduplicate fragments at runtime.

I wanted to do this at build time inside Babel but I can't find a way to do it ☹️

I copied the approach from `babel-plugin-graphql-tag`

### CODE REVIEW

File: src/utils/compileWithFragment.js [hunk 1]
```diff
@@ -1,6 +1,15 @@
 // @flow
 import gqlTag from 'graphql-tag';
 import serialize from 'babel-literal-to-ast';
+import template from '@babel/template';
+
+const uniqueFn = template.ast(`
```
Comment (FezVrasta) [inline src/utils/compileWithFragment.js]: Basically we append this function inside a `.reduce` call after the `.concat` we use to append the fragments.

**Comment by evenchange4** [comment]
Accept the PR for now. I have not come up with better solution to reduce runtime, either.
